[build]
  command = "npm run build"
  publish = "client/dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "https://backend-production-a7da.up.railway.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[context.production.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "https://backend-production-a7da.up.railway.app"calhost:5173"
